# Generated by Django 5.1.5 on 2025-02-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='assignment',
        #     name='created_at',
        # ),
        # migrations.RemoveField(
        #     model_name='assignment',
        #     name='updated_at',
        # ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='TopicDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='topic_diagrams/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='courses.topic')),
            ],
        ),
    ]
