# Generated by Django 5.1.5 on 2025-03-07 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='updated_at',
        ),
    ]
