# Generated by Django 5.1.5 on 2025-03-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_assignment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='completed_topics',
            field=models.ManyToManyField(blank=True, to='courses.topic'),
        ),
    ]
