# Generated by Django 5.1.5 on 2025-01-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='content',
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course_thumbnails/'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
