# Generated by Django 5.1.5 on 2025-03-08 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_topic_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentcourse',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topic',
            name='created_at',
        ),
    ]
