# Generated by Django 5.1.5 on 2025-03-18 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_studentcourse_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_cases', models.TextField(blank=True, help_text='Enter each test case on a new line.')),
                ('expected_output', models.TextField(help_text='Enter the expected output for each test case on a new line.')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_question', to='courses.question')),
            ],
        ),
        migrations.CreateModel(
            name='ShortAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.TextField()),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='short_answer', to='courses.question')),
            ],
        ),
    ]
