"""
Django settings for lumino_learn project.

Generated by 'django-admin startproject' using Django 3.1.14.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'a1f20@-1!nnbjm%ywa!g(!zf(70fh0a5d7g1ywn-k&f6+3dg1+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['luminolearn.onrender.com','127.0.0.1','localhost','*']

CSRF_TRUSTED_ORIGINS = [
    'https://luminolearn.onrender.com',
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

CSRF_COOKIE_SECURE = True  # For HTTPS
SESSION_COOKIE_SECURE = True  # For HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SAMESITE = 'Lax'
CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',  
    'rest_framework',
    'users',
    'courses',
    'dashboard',
    'gamification',
    'editor',
    'ai_engine',
    'chatbot',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', 
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'users.auth_backends.EmailAuthBackend',  # Custom email backend
    'django.contrib.auth.backends.ModelBackend',  # Default username backend
]



ROOT_URLCONF = 'lumino_learn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'lumino_learn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'lumino_learn',  # Your database name
#         'USER': 'postgres',  # Replace with your PostgreSQL username
#         'PASSWORD': 'Itsme@bhi143',  # Replace with your PostgreSQL password
#         'HOST': 'localhost',  # Use '127.0.0.1' if localhost doesn't work
#         'PORT': '5432',  # Default PostgreSQL port
#     }
# }

import os
import dj_database_url
from dotenv import load_dotenv
load_dotenv()  # Loads .env file for local development

# Base configuration - works for local development
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'DB_NAME'),
        'USER': os.getenv('DB_USER', 'DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'DB_HOST'),
        'PORT': os.getenv('DB_PORT', 'DB_PORT'),
    }
}

# Override with DATABASE_URL if present (for production on Render)
if 'DATABASE_URL' in os.environ:
    DATABASES['default'] = dj_database_url.config(
        default=os.environ['DATABASE_URL'],
        conn_max_age=600,
        conn_health_checks=True,
    )

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


MEDIA_URL = '/media/'  # URL prefix for media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory to store uploaded media

CODE_EVALUATION_TIMEOUT = 5  # seconds
MAX_CODE_MEMORY = '100m'     # 100MB



AUTH_USER_MODEL = 'users.CustomUser'
'''
LOGIN_REDIRECT_URL = '/users/dashboard/'
LOGOUT_REDIRECT_URL = '/users/login/'  # Optional logout redirect
'''

from dotenv import load_dotenv

load_dotenv()

# Chatbot

HF_API_TOKEN = os.getenv("HF_API_TOKEN")

COHERE_API_KEY = os.getenv('COHERE_API_KEYS')


# AI_ENGINE
# settings.py
from celery.schedules import crontab
from datetime import timedelta

CELERY_BEAT_SCHEDULE = {
    'retrain-weekly': {
        'task': 'ai_engine.tasks.retrain_model',
        'schedule': crontab(day_of_week='mon', hour=3),
        'kwargs': {'manual_trigger': False},
        'options': {'priority': 9}
    },
    'refresh-cache-daily': {
        'task': 'ai_engine.tasks.refresh_recommendations',
        'schedule': crontab(hour=4),
        'kwargs': {'precompute_active': True},
        'options': {'priority': 7}
    },
    'health-check-hourly': {
        'task': 'ai_engine.tasks.system_health_check',
        'schedule': timedelta(hours=1),
        'options': {'priority': 5}
    },
    'emergency-cache-fallback': {
        'task': 'ai_engine.tasks.emergency_cache_refresh',
        'schedule': timedelta(minutes=15),
        'options': {'priority': 3}
    }
}


MODEL_VERSION_KEY = 'lpr_current_model_version'
CACHE_BATCH_SIZE = 1500  # Optimal for Redis
CACHE_TTL = 86400 * 3  # 3 days


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',
    }
}